# Numpy

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


## Installing numpy

Using Anaconda: 

```bash
conda install numpy
```

using PyPI:
```bash
pip install numpy
```



In [8]:
#importing the numpy library
import numpy as np

In [5]:
%%time
a = []
for i in range(1000000):
    a.append(i)

CPU times: user 108 ms, sys: 28 ms, total: 136 ms
Wall time: 136 ms


In [9]:
%time b=np.arange(1000000)

CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 7.54 ms


In [2]:
# creating a zeros array
a = np.zeros(3)
a

array([0., 0., 0.])

In [3]:
# creating a 2d zeros array
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Knowing the type of an array
a.dtype

dtype('float64')

In [7]:
# Type conversion of a numpy array
a=a.astype(np.int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
# Getting to know that shape of the numpy array
a.shape

(3, 3)

In [9]:
# Reshaping the array arbitarily
a.shape=(9,1)
a

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [10]:
# Builtin functions for reshaping the array
a=a.reshape((3,3))
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
# creating a array in a range
a = np.arange(10)
a, a.shape

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), (10,))

In [13]:
np.exp(a)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [14]:
# Creating a linearly spaced array
a = np.linspace(2,10,5)
a

array([ 2.,  4.,  6.,  8., 10.])

In [15]:
# Converting a list to numpy array
a = np.array([i for i in range(10)])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# Exploring various operations of numpy array
print('sum of all elements of a', a.sum())
print('Standard Deviation of all elements of a', a.std())
print('Mean of a', a.mean())

sum of all elements of a 45
Standard Deviation of all elements of a 2.8722813232690143
Mean of a 4.5


In [17]:
# Slicing a numpy array
a[:5], a[5:]

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [18]:
# Creating a 2D numpy array
a = np.array([[i for i in range(10)],
              [i for i in range(100,110)]])
a

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [19]:
# Slicing a 2D numpy array
# array[row_slice, column_slice]
a[0,:5], a[1,8:]

(array([0, 1, 2, 3, 4]), array([108, 109]))

In [34]:
# Creating a random array
a=np.random.randint(0,100,10)
a

array([72, 39, 70, 70, 83, 66, 80, 73, 28, 90])

In [35]:
# Finding the index of maximum and the minimmum value 
print("Max element is {} at index {}.".format(a[a.argmax()], a.argmax()))
print("Min element is {} at index {}.".format(a[a.argmin()], a.argmin()))

Max element is 90 at index 9.
Min element is 28 at index 8.


In [64]:
np.random.seed(2)
a=np.random.randint(0,100,10)
a

array([40, 15, 72, 22, 43, 82, 75,  7, 34, 49])

In [65]:
a=np.random.randint(1,10,(3,3))
a

array([[6, 5, 5],
       [6, 8, 4],
       [7, 5, 4]])

In [68]:
a.T

array([[6, 6, 7],
       [5, 8, 5],
       [5, 4, 4]])

In [69]:
a.diagonal()

array([6, 8, 4])

In [70]:
a.trace()

18

In [71]:
a.flatten()

array([6, 5, 5, 6, 8, 4, 7, 5, 4])

In [73]:
a=np.arange(0,18,2).reshape(3,3)
b=np.arange(0,27,3).reshape(3,3).T
print(a)
print(b)

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
[[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]


[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
 
 [[ 0  9 18]
 [ 3 12 21]
 [ 6 15 24]]

In [74]:
np.dot(a,b)

array([[ 30,  84, 138],
       [ 84, 300, 516],
       [138, 516, 894]])

In [75]:
a*b

array([[  0,  18,  72],
       [ 18,  96, 210],
       [ 72, 210, 384]])

## Comparing the Speed of numpy modules

The use of numpy is mainly because of its speed of exection and so let us have a brief comparision of numpy with conventional python by creating 10 million numbers

In [76]:
num=10000000
a=[]
print('Conventional python time: ', end='')
%time for i in range(num): a.append(i)
print('List comprehension time: ', end='')
%time a=[i for i in range(num)]
print('Numpy time: ', end='')
%time a=np.arange(num)

Conventional python time: Wall time: 3.36 s
List comprehension time: Wall time: 1.76 s
Numpy time: Wall time: 343 ms


## Linear algebra using numpy

Numpy comes inbuilt with a operations to be performed on the matrices for performing linear algebra. This is found under _np.linalg_ class.

Let's try to solve this using an example


Let's say that we purchased 3 oranges and 5 apples for ₹ 65 and 4 Oranges and 3 Apples for ₹ 50. How will we find the cost of one Orange and one apple.

This could be solved using the system of equations formed as:
$$ a:= 3x+5y=65$$
$$ b:= 4x+3y=50$$

This equations are going to become something as:

$$
\left(\begin{array}{cc} 
3 & 5\\
4 & 3
\end{array}\right)
\left(\begin{array}{cc} 
x\\ 
y
\end{array}\right)
=
\left(\begin{array}{cc} 
65\\ 
50
\end{array}\right)
$$ 


Now to solve for the values of x and y, we are going to use the linear algebra module.

In [77]:
a=np.array([[3,5],[4,3]])
b=np.array([65, 50])
print(a, b)

[[3 5]
 [4 3]] [65 50]


In [78]:
[x,y]=np.linalg.solve(a,b)
print('Cost of Orange is {} \ncost of Apple is {}'.format(x,y))

Cost of Orange is 5.0 
cost of Apple is 10.0


In [79]:
inv_a = np.linalg.inv(a)
inv_a

array([[-0.27272727,  0.45454545],
       [ 0.36363636, -0.27272727]])

In [80]:
np.matmul(a,inv_a)

array([[1., 0.],
       [0., 1.]])

Read the documenations once at [Spacy documentations](https://docs.scipy.org/doc/)
or better download the [Numpy Guide](https://docs.scipy.org/doc/_static/numpybook.pdf)